---
- name: Check required proxmox_backup.server dictionary keys
  ansible.builtin.fail: msg="proxmox_backup.server.{{ required_key }} must be defined"
  when: required_key not in proxmox_backup.server
  with_items: "{{ required_pbs_server_keys }}"
  loop_control:
    loop_var: required_key

- name: Check required proxmox_backup.client dictionary keys
  ansible.builtin.fail: msg="proxmox_backup.client.{{ required_key }} must be defined"
  when: required_key not in proxmox_backup.client
  with_items: "{{ required_pbs_client_keys }}"
  loop_control:
    loop_var: required_key

- name: Check required proxmox_backup.archive dictionary keys
  ansible.builtin.include_tasks: check_archive_keys.yaml
  with_items: "{{ proxmox_backup.client.archives }}"
  loop_control:
    loop_var: archive

- name: Check required proxmox_backup.exclude dictionary keys
  ansible.builtin.include_tasks: check_exclude_keys.yaml
  with_items: "{{ proxmox_backup.client.exclude }}"
  loop_control:
    loop_var: exclude
  when: proxmox_backup.client.exclude is defined

# - name: Merge supplied and default dictionaries
#   ansible.builtin.set_fact:
#     config: "{{ default_config | combine(proxmox_backup, recursive=true) }}"

- name: Include OS Family tasks
  ansible.builtin.include_tasks: os/{{ ansible_os_family | lower }}.yaml

- name: Configure encryption
  ansible.builtin.include_tasks: encryption.yaml
  when:
    - proxmox_backup.client.encrypt is defined
    - proxmox_backup.client.encrypt.enable

- name: Add Exclusions
  ansible.builtin.include_tasks: exclude.yaml
  loop: "{{ proxmox_backup.client.exclude }}"
  loop_control:
    loop_var: exclude
  when: proxmox_backup.client.exclude is defined

# - name: Debug Config
#   debug:
#     var: proxmox_backup.client

# - name: Configure service
#   include_tasks: service.yaml

- name: Proxmox Backup Server | Construct ExecStart command
  ansible.builtin.set_fact:
    proxmox_backup_client_start_cmd: |-
      /usr/bin/proxmox-backup-client
      {% if proxmox_backup.server.encrypt.key is defined %}
      --keyfile {{ proxmox_backup.client.encrypt.key | default('~/.config/proxmox-backup/encryption-key.json') }}
      {% endif %}
      --skip-lost-and-found {{ proxmox_backup.client.skip_lost_found | default('false') }} \
      {% if proxmox_backup.client.include_devices is defined %}
      {% for dev in proxmox_backup.client.include_devices %}
      --include-dev {{ dev }} \
      {% endfor %}
      {% endif %}
      {% for archive in proxmox_backup.client.archives %}
      {{ archive.name }}{{ archive.format }}:{{ archive.path }}{{ " \\" if not loop.last else '' }}
      {% endfor %}

- name: Proxmox Backup Server | Create systemd service
  ansible.builtin.include_role:
    name: notmycloud.systemd_unit
  vars:
    systemd_units:
      root:
        service:
          proxmox-backup-client:
            config:
              Unit:
                Description: Proxmox Backup Client
                Requires: network-online.target
                After: network-online.target
              Service:
                Type: oneshot
                Environment:
                  - PBS_REPOSITORY={{ proxmox_backup.server.user }}@{{ proxmox_backup.server.host }}{% if proxmox_backup.server.port is defined %}:{{ proxmox_backup.server.port }}{% endif %}:{{
                    proxmox_backup.server.datastore }} # noqa line-length
                  - PBS_PASSWORD={{ proxmox_backup.server.pass }}
                  - PBS_FINGERPRINT={{ proxmox_backup.server.fingerprint | default(omit) }}
                  - PBS_ENCRYPTION_PASSWORD={{ proxmox_backup.client.encrypt.pass | default(omit) }}
                  - PBS_OUTPUT_FORMAT={{ proxmox_backup.client.output.format | default('text') }}
                  - PBS_OUTPUT_NO_BORDER={{ proxmox_backup.client.output.border | default(omit) }}
                  - PBS_OUTPUT_NO_HEADER={{ proxmox_backup.client.output.header | default(omit) }}
                ExecStart:
                  - "{{ proxmox_backup_client_start_cmd | trim | regex_replace('\n+', ' \\\n') | indent(4, False) }}"
        timer:
          proxmox-backup-client:
            config:
              Unit:
                Description: Proxmox Backup Client Trigger
              Timer:
                OnCalendar: "{{ proxmox_backup.client.schedule.calendar | default('*-*-* 4:00:00') }}"
                Persistent: "{% proxmox_backup.client.schedule.runifmissed | default('false') %}"
              Install:
                WantedBy: timers.target
